# Current Supabase Configuration (backup)
CURRENT_SUPABASE_URL = "https://zbwvjaqvqfdywxxpsekd.supabase.co"
CURRENT_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpid3ZqYXF2cWZkeXd4eHBzZWtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMzk0NTAsImV4cCI6MjA2ODYxNTQ1MH0.xcXGJHBFYp6Aj77ZNJTjD8L6EWZ5ErJ-iDzDGhK2yAw"

# Replace these with your NEW Supabase project credentials:
SUPABASE_URL = "https://YOUR_NEW_PROJECT.supabase.co"
SUPABASE_ANON_KEY = "YOUR_NEW_ANON_KEY"

# Section for supabase (used by app)
[supabase]
url = "https://YOUR_NEW_PROJECT.supabase.co"
key = "YOUR_NEW_ANON_KEY"
