# Streamlit Secrets Configuration Template
# Copy this file to .streamlit/secrets.toml and fill in your credentials

# === SUPABASE CONFIGURATION ===
# Get these from your Supabase project settings
# SUPABASE_URL = "https://your-project.supabase.co"
# SUPABASE_ANON_KEY = "your-anon-key"
# SUPABASE_SERVICE_KEY = "your-service-key"  # Optional, for admin operations

# === MONGODB ATLAS CONFIGURATION ===
# Get this from your MongoDB Atlas cluster connection string
# MONGODB_CONNECTION_STRING = "mongodb+srv://username:password@cluster.mongodb.net/"
# MONGODB_DATABASE = "flora_fauna_db"

# === AIRTABLE CONFIGURATION ===
# Get these from your Airtable account
# AIRTABLE_API_KEY = "your-api-key"
# AIRTABLE_BASE_ID = "your-base-id"
# AIRTABLE_TABLE_NAME = "collected_data"

# === FIREBASE CONFIGURATION ===
# Download your service account JSON from Firebase console
# FIREBASE_PROJECT_ID = "your-project-id"
# [FIREBASE_CREDENTIALS]
# type = "service_account"
# project_id = "your-project-id"
# private_key_id = "your-private-key-id"
# private_key = "-----BEGIN PRIVATE KEY-----\nYOUR_PRIVATE_KEY\n-----END PRIVATE KEY-----\n"
# client_email = "your-service-account@your-project.iam.gserviceaccount.com"
# client_id = "your-client-id"
# auth_uri = "https://accounts.google.com/o/oauth2/auth"
# token_uri = "https://oauth2.googleapis.com/token"
# auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
# client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/your-service-account%40your-project.iam.gserviceaccount.com"

# === INSTRUCTIONS ===
# 1. Choose one or more database providers above
# 2. Uncomment the relevant sections
# 3. Fill in your actual credentials
# 4. Save this file as .streamlit/secrets.toml
# 5. For Streamlit Cloud: Add these as secrets in your app settings

# === SECURITY NOTES ===
# - Never commit this file with real credentials to version control
# - Add .streamlit/secrets.toml to your .gitignore
# - Use environment variables in production
# - Rotate credentials regularly
